### PR TITLE
moved all problems to Day-1 folder

### PR DESCRIPTION
**Pull request by Gauravsinghal09**

### CODE REVIEW

**Comment by zahlekhan** [comment]
Cannot review PR since this is only a rename commit

**Comment by Gauravsinghal09** [comment]
> Cannot review PR since this is only a rename commit

Please have a look at slack

https://github.com/Gauravsinghal09/freshers-bootcamp/commit/61955387b0b63545ae144ae96dd5f7342c5ff28e

**Comment by Gauravsinghal09** [comment]
> > Cannot review PR since this is only a rename commit
> 
> Please have a look at slack
> 
> [6195538](https://github.com/Gauravsinghal09/freshers-bootcamp/commit/61955387b0b63545ae144ae96dd5f7342c5ff28e)

You can use this commit to review the code https://github.com/Gauravsinghal09/freshers-bootcamp/commit/61955387b0b63545ae144ae96dd5f7342c5ff28e

**Comment by zahlekhan** [comment]
I have added my comments on [6195538](https://github.com/Gauravsinghal09/freshers-bootcamp/commit/61955387b0b63545ae144ae96dd5f7342c5ff28e)

**Pull request merged**
